### ISSUE TITLE
More enhancement's that could be added

### ISSUE THREAD

**Issue by f0rmatme** [Vaalyn/sylius-shop#7]
https://github.com/JoppeDC/SyliusBetterSeoPlugin Adds configurable SEO meta tags and image to taxon pages. / products 
https://github.com/aropixel/sylius-admin-media-plugin Media management

**Comment by Vaalyn** [comment]
I've added the SEO plugin and tried to add the media management plugin but the documentation is not really up to date. After correcting a lot of stuff I've got it installed but it's just not working correctly. I might get back to test it again later but at the moment it does not seem to be a good choice to include it yet.
